# Multiple linear regression

독립변수가 2개 이상인 경우의 회귀를 Multiple linear regression이라고 한다.

### 필요한 library를 Import

In [1]:
# For these lessons we will need NumPy, pandas, matplotlib and seaborn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# and of course the actual regression (machine learning) module
from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
# Load the data from a .csv in the same folder
data = pd.read_csv('https://raw.githubusercontent.com/aonekoda/reference/main/data/1.02.%20Multiple%20linear%20regression.csv')

# Let's explore the top 5 rows of the df
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
# This method gives us very nice descriptive statistics. We don't need this for now, but will later on!
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Create the multiple linear regression

### Declare the dependent and independent variables
종속변수와 독립변수를 선언한다.

In [4]:
# There are two independent variables: 'SAT' and 'Rand 1,2,3'
x = data[['SAT','Rand 1,2,3']]

# and a single depended variable: 'GPA'
y = data['GPA']

### Regression 모형의 생성

In [5]:
# We start by creating a linear regression object
reg = LinearRegression()

# The whole learning process boils down to fitting the regression
reg.fit(x,y)

LinearRegression()

In [6]:
# Getting the coefficients of the regression
reg.coef_
# Note that the output is an array

array([ 0.00165354, -0.00826982])

In [7]:
# Getting the intercept of the regression
reg.intercept_
# Note that the result is a float as we usually expect a single value

np.float64(0.29603261264909486)

### 모형의 평가 - Calculating the R-squared

결정계수를 확인한다. 모형의 설명력을 확인할 수 있다.

In [8]:
# Get the R-squared of the regression
reg.score(x,y)

0.4066811952814283

### 모형의 평가 - Formula for Adjusted $R^2$

독립변수를 계속적으로 추가하면 모형의 설명력은 증가한다.  
불필요하게 설명력이 없는 변수가 추가 되었을 때 이를 보정하는 방법이 바로 adj $R^2$ 이다.  

adj $R^2$ 는 다음과 같은 공식으로 계산 가능하다.  

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [9]:
# Get the shape of x, to facilitate the creation of the Adjusted R^2 metric
x.shape

(84, 2)

In [10]:
# If we want to find the Adjusted R-squared we can do so by knowing the r2, the # observations, the # features
r2 = reg.score(x,y)
# Number of observations is the shape along axis 0
n = x.shape[0]
# Number of features (predictors, p) is the shape along axis 1
p = x.shape[1]

# We find the Adjusted R-squared using the formula
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

### 모형의 평가 - MSE

모형의 예측값과 실제값 사이의 차이가 작을수록 좋은 모형으로 평가할 수 있다.

In [11]:
from sklearn.metrics import mean_squared_error, root_mean_squared_error

y_true = y
y_pred = reg.predict(x)

mse = mean_squared_error(y_true, y_pred)
rmse = root_mean_squared_error(y_true, y_pred)

print("MSE = ", mse, "\tRMSE = ", rmse)

MSE =  0.043251494565310245 	RMSE =  0.20796993668631591


## 실습하기

1. 다음과 같이 샘플 데이터셋을 읽어 들이시오.
```
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/aonekoda/reference/main/data/housing.data.txt')
data.info()
```

2. 읽어들인 보스턴 집값을 예측하는 회귀모형을 생성하시오.
3. 생성된 모형을 평가하시오.

In [1]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/aonekoda/reference/main/data/housing.data.txt')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [2]:
# For these lessons we will need NumPy, pandas, matplotlib and seaborn
import numpy as np
import matplotlib.pyplot as plt

# and of course the actual regression (machine learning) module
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error
from sklearn.model_selection import train_test_split

In [15]:
X = data.values[:, :-1]
y = data.values[:, -1:]
X, y

(array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]], shape=(506, 13)),
 array([[24. ],
        [21.6],
        [34.7],
        [33.4],
        [36.2],
        [28.7],
        [22.9],
        [27.1],
        [16.5],
        [18.9],
        [15. ],
        [18.9],
        [21.7],
        [20.4],
        [18.2],
        [19.9],
        [23.1],
        [17.5],
        [20.2],
        [18.2],
        [13.6],
        [19.6],
        [15.2],
        [14.5],
        

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)
model.score(X,y)

0.7360862848114996

In [20]:
model.score(X_test, y_test)

0.6844267283527145

In [21]:
print(model.coef_, model.intercept_)

[[-1.28322638e-01  2.95517751e-02  4.88590934e-02  2.77350326e+00
  -1.62388292e+01  4.36875476e+00 -9.24808158e-03 -1.40086668e+00
   2.57761243e-01 -9.95694820e-03 -9.23122944e-01  1.31854199e-02
  -5.17639519e-01]] [29.83642016]
